---
title: "visualizationLitReview"
author: "Maria Heeter"
date: "2/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# census, etc 
library(readxl)
library(censusapi)
library(tidycensus)
library(tidyverse)
library(viridis)
library(dplyr)
library(tidyr)
library(reshape2)
# maps 
library(maps)
library(usmap)
library(ggplot2)
```

## loads in both datasets 

```{r cars, echo=FALSE}
# imports CPI Rent/ HPI sep graph 
RentHpiSep <- read_excel("CPI Rent and HPI (separated).xls",skip = 11)

# imports joint CPI/HPI graph 
RentHpiJoint <- read_excel("All-Transactions House Price Index for the United States:Consumer Price Index for All Urban Consumers- Rent of Primary Residence in U.S. City Average.xls", 
    skip = 10)

```

## Including Plots

``` {r, echo=FALSE}
library("ggplot2")
library("ggthemes")
library("stringr")

joinedPlot <- ggplot(RentHpiJoint, aes(x=observation_date,y=RentHpiJoint$USSTHPI_CUUR0000SEHA )) + geom_line() + ylab("Index 1980:Q1=100/Index 1982-1984=100") + xlab("Date of Observation") + labs(caption = "Sources: FHFA; BLS")

#labs(title = str_wrap("All-Transactions House Price Index for the United States/Consumer Price Index for All Urban Consumers: Rent of Primary Residence in U.S. City Average", 60))

joinedPlot + theme_stata()


                                     
```

```{r, echo=FALSE}

sepPlot <-  ggplot() + geom_line(data = RentHpiSep, aes(x=observation_date...1, y=CUSR0000SEHC), color="blue") + geom_line(data=RentHpiSep, aes(x=observation_date...4, y=USSTHPI), color="red") + ylab("Index Dec 1982=100, Index 1980:Q1=100") + xlab("Date of Observation") + labs(caption="Sources: FHFA; BLS")

sepPlot + theme_stata()

```

## map of SMSAs 

```{r, include=FALSE, echo=FALSE}

library(tidycensus)
library(tidyverse)
library(tigris)
library(usmap)
options(tigris_use_cache=TRUE)

state_overlay <- states(
  cb = TRUE,
  resolution = "20m"
) %>%
  filter(GEOID != "72") %>%
  shift_geometry()

mapPlot <- ggplot() + geom_sf(data = state_overlay, fill = NA, color = "black", size = 0.1)

mapPlot

# recall: check email, then supply the key to the census_api_key function to use it throughout tidycensus session. 

usmap::plot_usmap

```
## Api Set up 

```{r, API setup}
# getting started w censusapi 
# sign up for an API key 

# add key to .Renviron 
Sys.setenv(CENSUS_KEY="6d7ca29c7ed75ec60a626822e88603fa6231567c")

# reload .Renviron 
readRenviron("~/.Renviron")

# check to see that expected key is output in R console 
Sys.getenv("CENSUS_KEY")
```

## Finding your API 
 
```{r}
# getting started - load the censusapi library 
library(censusapi)

# to see a list of available end points 
apis <- listCensusApis()
View(apis)
``` 

## Loading in data 

```{r, echo=FALSE}

census_api_key("6d7ca29c7ed75ec60a626822e88603fa6231567c", install=TRUE,overwrite=TRUE)

# api key can be accessed: Sys.getenv("CENSUS_API_KEY").
```

```{r}
# time series: use the tidycensus function "get estimates() to get pop estimates by county for each year beg. in 2010 
# computing a time series estimate 

years <- 2009:2019
names(years) <- years

priceVars <- c(contract_rent="B25056_001", housing_value="B25077_001",population="B01003_001", median_age_by_sex="B01002_001") # 

pricesByYear <- map_dfr(years, ~{get_acs(geography="county", variables=priceVars, survey="acs1", year=.x
                                         )
  },.id="year")

view(pricesByYear) #here, the housing figure is correct # updated, yes, it's correct 

# description of the data used (UPDATE THIS!!) 

# ** one year estimates ** B25075_001E is Value for owner-occupied housing units. description: the respondent's estimate of how much the property (house and lot, mobile home and lot, or condominium unit) would sell for if it were for sale.

# description: https://www.socialexplorer.com/data/ACS2010/metadata/?ds=ACS10&var=B25075001
  
# ** one year estimates ** B25056_001E is Contract Rent for Renter-occupied housing units. The data on contract rent (also referred to as "rent asked" for vacant units) were obtained from Housing Question 18a in the 2013 American Community Survey. The question was asked at occupied housing units that were for rent, vacant housing units that were for rent, and vacant units rented but not occupied at the time of interview.

# description: https://www.socialexplorer.com/data/ACS2016/metadata/?ds=ACS16&table=B25056

# data not used, but considered: # ** one year estimates ** B25031_001E is MEDIAN GROSS RENT BY BEDROOMS. description: Median gross rent divides the gross rent distribution into two equal parts: one-half of the cases falling below the median gross rent and one-half above the median. Median gross rent is computed on the basis of a standard distribution. (See the "Median Standard Distributions" section in Appendix A). Median gross rent is rounded to the nearest whole dollar. The median gross rent explanation is comparable to the description used for Median and Quartile Contract Rent. (For more information on medians, see "Derived Measures.")

# description: https://www.socialexplorer.com/data/ACS2015/metadata/?ds=ACS15&var=B25031001

```

## here we can see each variable by dataset  

```{r}
v19 <- load_variables(2019, "acs1", cache=FALSE)
view(v19)

v09 <- load_variables(2009, "acs1", cache=FALSE)
view(v09)

```

## reshaping data 

```{r}
# long to wide using dcast() function in R: gets the table name and the list of columns to be kept constant (counties) and list of columns to be reshaped (variable) is passed as argument to reshape from long to wide 

long_to_wide = dcast(pricesByYear, year + GEOID + NAME ~ variable, value.var = "estimate")
view(long_to_wide) # NOTE: getting rid of margin of error 

```

## adding new variables 

```{r}
# note: here, we'll turn to the description in other papers of which counties were selected

# need to insert: need

# 1) the real annual rent growth rate in area i between years t and t+1, (g)
# 2) the rent-price ratio for area i in year t. (Rt / Pt)

# first, inserting the rent growth rate 

rent_growth_rate = long_to_wide %>% group_by(GEOID) %>% arrange(year) %>% mutate(diff_year = strtoi(year) - lag(strtoi(year)), diff_growth = contract_rent - lag(contract_rent), rate_percent = (diff_growth/diff_year)/contract_rent * 100)
# view 
view(rent_growth_rate)

# check that this works w prof. kacher 

# now, calculate rent-price ratio for area i in year t (Rt/Pt)

rent_price_ratio = rent_growth_rate %>% group_by(GEOID) %>% arrange(year) %>% mutate(rent_price_ratio= contract_rent/housing_value)
# view 
view(rent_price_ratio)

# get rid of figures missing either rent or housing prices using tidyr method 
rent_price_ratio = rent_price_ratio %>% drop_na(contract_rent) 
rent_price_ratio = rent_price_ratio %>% drop_na(housing_value)
view(rent_price_ratio)

# now, add in the price deflator for personal consumption expenditures excluding good & energy to deflate nominal values

# load in price deflator dataset 

priceDeflator <- read_csv("priceDeflator.csv")
priceDeflator = subset(priceDeflator, select = -c(...1) ) # gets rid of extra row 
view(priceDeflator)

# adds price deflator by year 

rent_price_ratio <- merge(rent_price_ratio, priceDeflator,by="year")
view(rent_price_ratio)

# separating county into county, state 

# split NAME column into county name and state 
rent_price_ratio <- rent_price_ratio %>% separate(NAME, c("county_name", "state_name"), ", ")
view(rent_price_ratio) # it works! don't run line above, as it's been sepped, unless in order / running all 
```

```{r}
# data visualization & summary stats 

# installed dev tools ( following this tutorial https://urban-institute.medium.com/how-to-create-state-and-county-maps-easily-in-r-577d29300bb2)

# trying out maps 

library(urbnmapr)

# test of state map 

states_sf <- get_urbn_map("states", sf = TRUE)

states_sf %>% 
  ggplot(aes()) +
  geom_sf(fill = "grey", color = "#ffffff")

# test of county map 

counties_sf <- get_urbn_map("counties", sf = TRUE)
counties_sf %>% ggplot(aes()) + geom_sf(fill="grey", color="#ffffff")

# now, joining fips code by county name should work 

# mappingData <- semi_join(rent_price_ratio, urbnmapr::counties, by=c("GEOID"="county_fips")
# glimpse(mappingData)
# view(mappingData)

# that didn't work 

# changing col name 
colnames(rent_price_ratio)[colnames(rent_price_ratio)=="GEOID"] <- "fips"
view(rent_price_ratio)

```

## adds some more variables 

```{r}
# adding growth rate for house prices 

rent_price_ratio <- rent_price_ratio %>% group_by(fips) %>% arrange(year) %>% mutate(diff_housing_growth = housing_value - lag(housing_value), growth_rate_housing = (diff_housing_growth/diff_year)/housing_value * 100) # new - old = diff, growth rate is diff/1 * 100 

view(rent_price_ratio)

# renames 

df <- rent_price_ratio

# adds median value for rent price ratio, housing value, contract rent, rate percent, housing growth rate

df <- df %>% group_by(fips) %>% arrange(year) %>% mutate(mean_rent_price_ratio = mean(rent_price_ratio, na.rm=TRUE)) # stripping the NAs

df <- df %>% group_by(fips) %>% arrange(year) %>% mutate(mean_housing_value = mean(housing_value, na.rm=TRUE)) # strip NAs

df <- df %>% group_by(fips) %>% arrange(year) %>% mutate(mean_contract_rent = mean(contract_rent, na.rm=TRUE)) # strip NAs

df <- df %>% group_by(fips) %>% arrange(year) %>% mutate(mean_rent_pct_change = mean(rate_percent, na.rm=TRUE)) #  strip NAs 

df <- df %>% group_by(fips) %>% arrange(year) %>% mutate(mean_housing_growth = mean(growth_rate_housing, na.rm=TRUE)) # strip NAs

view(df)
                                                            
```

# map building 

```{r}

usmap::plot_usmap(regions = "counties") # sample map 

# take the average of each of these values 

rent_price_ratio_map <- plot_usmap(data = df, values="mean_rent_price_ratio", include = c(df$fips), color="black") + scale_fill_gradientn(name="Average Rent-Price Ratio (2006-2019)", colours = c("blue", "white", "darkred"), label = scales::comma) + theme(legend.position="right")
rent_price_ratio_map # fix label 

housing_value_map <- plot_usmap(data = df, values="mean_housing_value", include = c(df$fips), color="black") + scale_fill_gradientn(name="Average Housing Value (2006-2019)", colours = c("blue", "white", "darkred"), label = scales::comma) + theme(legend.position="right")
housing_value_map 

rent_value_map <- plot_usmap(data = df, values="mean_contract_rent", include = c(df$fips), color="black") + scale_fill_gradientn(name="Average Contract Rent (2006-2019)", colours = c("blue", "white", "darkred"), label = scales::comma) + theme(legend.position="right")
rent_value_map 

# rent growth gradient map 

rent_growth_map <- plot_usmap(data = df, values="mean_rent_pct_change", include = c(df$fips), color="black") + scale_fill_gradientn(name="Average Rent Percent Change (2006-2019)", colours = c("blue", "white", "darkred"), breaks=c(10,-20), label = scales::comma) + theme(legend.position="right")
rent_growth_map 
                       
# housing percent change in growth take 1 

housing_growth_map <- plot_usmap(data = df, values="mean_housing_growth", include = c(df$fips), color="black") + scale_fill_continuous(low="blue", high="red", name="Median Housing Growth (2006-2019)", label=scales::comma) + theme(legend.position="right")
housing_growth_map 

# housing percent change in growth take 2 

housing_growth_map <- plot_usmap(data = df, values="mean_housing_growth", include = c(df$fips), color="black") + scale_fill_gradientn(name="Average Housing Price Growth (2006-2019)", colours = c("blue", "white", "red"), breaks=c(10,-20), label = scales::comma) + theme(legend.position="right")
housing_growth_map
                                                                                                                                     
                                                                                                                                  
# how to make negative: https://stackoverflow.com/questions/63004413/r-usmap-how-to-show-two-different-colors-one-for-gradients-in-positive-value

# notes on summary stats for time series 

# sum doesn't deliniate cross sectional data (but include in appencix)
# time plots, maps 
# rent-price ratio figure & map. avg rent-price ratio overtime 

# three plots: 
# rent over time, hp over time & ratio 

```
# notes 

```{r}
# generally, are there other demographics that could be helpful?

# population 
# income 
# racial demographics 
# employment rates 
# age 

# hundreds of thousands 

# do everything w counties 
# maybe sub samples w different criteria later 

# do summary stats... data visualization 
# mapping 
# by county averaging rent price ratio over time period, mapping that # visualize rate of change by county 

# combo of time plots and maps 
# is there variation? are there patterns in the variation? 

```

# summary stats 

```{r}

```



