---
title: "regressions"
author: "Maria Heeter"
date: "3/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(censusapi)
library(tidycensus)
library(tidyverse)
library(viridis)
library(dplyr)
library(tidyr)
library(reshape2)
# maps 
library(maps)
library(usmap)
library(ggplot2)
# regressions 
library(AER)
library(dynlm)
library(forecast)
library(readxl)
library(stargazer)
library(scales)
library(quantmod)
library(urca)
library(Formula)
library(plm)
library(sandwich)
```
 
# insert data 

```{r}
# load in df 
df <- read.csv("thesisDF.csv")
view(df)
```

## Final dataset additions to run regressions 

```{r}
# note: I can't find the initial thing i wrote down re regressions to include 
 
# regression equation is as follows: 

#gi\, t+1 = x + B(Ri,t/Pi,t) + ei, t+10 

# where gi rep annual real rent growth in area i between years t and t + 1 and Ri/Pi rep the annual rent-price ratio for area i in year t 

# notes: cross-section data for years t and t+10 are cross sectional 

# view(df)
# 
# # real rent growth 
# df <- df %>% group_by(fips) %>% arrange(year) %>% mutate(real_rent_growth = diff_growth*GDPDEF)
# 
# # real contract rent 
# df<- df %>% group_by(fips) %>% arrange(year) %>% mutate(real_contract_rent = contract_rent*GDPDEF)
# 
# # real rent percent growth 
# df <- df %>% group_by(fips) %>% arrange(year) %>% mutate(real_rent_perc_growth = (real_rent_growth/diff_year)/real_contract_rent)
# glimpse(df)
#                           
```

## Regressions 

```{r}
# messing around 
# # https://www.econometrics-with-r.org/14-ittsraf.html FOR CONTEXT 
# real_rent_perc_growth = x + beta(rent/price)
# call: 
# modelTEST <- lm(formula = real_rent_perc_growth = x + beta(rent_price_ratio) + standard error 
# if investors expect future rent to grow at a constant annual rate as the gordon formulation, Beta should = -1. 
# simple call: 

# model <- lm(real_rent_perc_growth ~ rent_price_ratio, data=df)
# coeftest((model, vcov.=vcovHAC))
# model
# summary(model)
# 
# # convert series to xsts objects 
# 
# df_ts <- ts(df, start=c(2009), frequency=11)
# print(df_ts)
# 
# # get rid of extra time series objects 
# 
# df <- df %>% subset(select=-c(X.1, X))
# view(df)
# 
# df_prep <- df %>% group_by(fips) 
# df_test_ts <- ts(df_prep, start=c(2009), frequency=11)
# print(df_test_ts)
# 
# ### trying again: 
# 
# # need to make dataframe into time series 
# 
# df_test <- df %>% group_by(fips) <- ts(start=c(2009, ))

```

# modeling 

```{r}

# transform data 

df_reg <- pdata.frame(df, index="Date")
index(df_reg) # checks ts ... seems wrong(?) 

simpletestFips <- plm(real_rent_perc_growth ~ rent_price_ratio, data=df, index="fips", model="within")
simpletestFips # should index be fips or year? 

# test: 

simpletestYr <- plm(real_rent_perc_growth ~ rent_price_ratio, data=df, index="year", model="within")
simpletestYr

# preg <- plm(real_rent_perc_growth ~ rent_price_ratio, data=df, model="within", effect="twoways")
# 
# # model 
# modelTEST <- plm(real_rent_perc_growth ~ rent_price_ratio, data=df, model="within", random.method="swar") # within is fe model
# modelTES

```

# estimate simple reg model using 2009 data 

```{r}
# subset the data 
rentPriceRatio2010 <- subset(df, year == "2010")
rentPriceRatio2012 <- subset(df, year == "2012")

# estimate simple reg models 
reg2010sub <- lm(real_rent_perc_growth ~ rent_price_ratio, data=rentPriceRatio2010)
reg2012sub <- lm(real_rent_perc_growth ~ rent_price_ratio, data=rentPriceRatio2012)

# t tests 
coeftest(reg2010sub, vcov. = vcovHC, type="HC1")
coeftest(reg2012sub, vcov. = vcovHC, type="HC1")

# viz of first reg line 
plot(x = rentPriceRatio2010$rent_price_ratio, y = rentPriceRatio2010$real_rent_perc_growth, xlab = "Rent-Price Ratio (2010)", ylab = "Real Rent Percent Growth Rate (2010)", ylim = c(0, .4), pch = 20, col = "steelblue")
abline(reg2010sub, lwd = 1.5)

# viz of second 
plot(x = rentPriceRatio2012$rent_price_ratio, y = rentPriceRatio2012$real_rent_perc_growth, xlab = "Rent-Price Ratio (2012)", ylab = "Real Rent Percent Growth Rate (2012)", ylim = c(0, .4), pch = 20, col = "steelblue")
abline(reg2012sub, lwd = 1.5)

# note: see for info: https://www.econometrics-with-r.org/10.1-panel-data.html
```

```{r}
# unfortunately i think i need to add month and years to each year in order to treat is as ts 

# add column of month and day (01 and 1 respectively)
# 
# dfTEST <- df %>% mutate(month = 01) %>% mutate(day = 01)
# view(dfTEST)
# 
# # need to make month, days into integer instead of numeric 
# 
# dfTEST$month <- as.character(dfTEST$month)
# dfTEST$day <- as.character(dfTEST$day)
# dfTEST$year <- as.character(dfTEST$year)
# # checking class 
# class(dfTEST$day)
# class(dfTEST$month)
# class(dfTEST$year)
# # all are integers 
# 
# # now create new col named as "Date" by combining cols 
# dfTEST$Date <- as.Date(with(dfTEST, paste(year,month,day,sep='-')), "%Y-%m-%d")
# view(dfTEST)
# 

```

# plm fixed effects regression 
# question: is the real_rent_perc_growth correct for the year? would it be one ahead? 
```{r}
mod <- plm(real_rent_perc_growth ~ rent_price_ratio, data=df, index=c("Date", "fips"), model='within')
coeftest(mod, vcov.=vcovHC, type="HC1")

# try again w na's omited 
mod <- plm(real_rent_perc_growth ~ rent_price_ratio, data=df, index=c("Date", "fips"), model='within')
coeftest(mod, vcov.=vcovHC, type="HC1")

# est coeff is .007 -- the coeff on _ is negative and significant. the interpretation is that the est reduction in rent perc growth due to an increase in the rent_price_ratio by 1 is .007. "although including [fips] fixed effects eliminates the risk of a bias due to omitted factors that vary across states but not over time, we suspect that there are other omitted variables that vary over time and thus cause a bias."

# general reg plot & reg line 
plot(x = df$rent_price_ratio, y = df$real_rent_perc_growth, xlab = "Rent-Price Ratio (2009 - 2019)", ylab = "Real Rent Percent Growth Rate (2009 - 2019)", ylim = c(0, .4), pch = 20, col = "steelblue")
abline(mod, lwd = 1.5)
```

# estimate combined time and entity fixed eff reg model 

```{r}
lm_mod <- lm(real_rent_perc_growth ~ rent_price_ratio + fips + year - 1, data=df)
lm_mod

# model via plm 

lm_mod_plm <- plm(real_rent_perc_growth ~ rent_price_ratio, data = df, index = c("fips", "year"), model="within", effect="twoways")
coeftest(lm_mod_plm, vcov=vcovHC, type="HC1")

# before disc outcomes remind that state and year are of class factor 
class(df$fips)
class(df$year)

# changes to factor using test dataset 
dfTEST <- df 
dfTEST$fips <- as.factor(df$fips)
dfTEST$year <- as.factor(df$year)
class(dfTEST$year)

# tries again 
lm_mod_plm <- plm(real_rent_perc_growth ~ rent_price_ratio, data = dfTEST, index = c("fips", "year"), model="within", effect="twoways")
coeftest(lm_mod_plm, vcov=vcovHC, type="HC1") # note: twoways includes entity and time dummies. adds the addtl regressor year for time fixed effects. 

# plots above model 
plot(x = dfTEST$rent_price_ratio, y = dfTEST$real_rent_perc_growth, xlab = "Rent-Price Ratio (2009-2019)", ylab = "Real Rent Percent Growth Rate (2009-2019)", ylim = c(0, .4), pch = 20, col = "steelblue")
abline(lm_mod_plm, lwd = 1.5)

# see: https://www.econometrics-with-r.org/10.4-regression-with-time-fixed-effects.html

# obtains a summary based on clustered standard errors (plm). adjusts for autocorrelation AND heteroskedasticity. 
coeftest(lm_mod_plm, vcov=vcovHC, type="HC1")

# obtains a summary based on heteroskedasticity-robust standard errors (no adj for heterosked. only)
coeftest(lm_mod, vcov = vcovHC, type="HC1")[1,]

# checks class of both models 
class(lm_mod_plm) # panel 
class(lm_mod) # lm 

# now, discuss results: 
```
 
 # discussion of all seven models 
```{r}
mod1 <- lm(real_rent_perc_growth ~ rent_price_ratio, data=df)
mod1

mod2 <- plm(real_rent_perc_growth ~ rent_price_ratio + fips, index="fips", data=df) # note: i altered the code to make fips index... 
mod2

mod3 <- plm(real_rent_perc_growth ~ rent_price_ratio + fips + year, index = c("fips", "year"), model = "within", effect="twoways", data=df)
mod3 

# in mod4, we want to include other county specific variables (we can pull this from the api!)
 
#eg

mod4 <- plm(real_rent_perc_growth ~ rent_price_ratio + fips + year + population, index = c("fips", "year"), model="within", effect="twoways", data=df)
mod4

```

# stargazer section 

```{r}
# gather clustered standard errors in a list 

se <- list(sqrt(diag(vcovHC(mod1, type="HC1"))), sqrt(diag(vcovHC(mod2, type="HC1"))), sqrt(diag(vcovHC(mod3, type="HC1"))), sqrt(diag(vcovHC(mod4, type="HC1"))))

# generate the table 

# tableTEST <- stargazer(mod1, mod2, mod3, mod4, header=FALSE, se=se, title="Linear Panel Regression Models of Rent Growth and Rent-Price-Ratio", model.numbers=FALSE, column.labels=c("(1)", "(2)", "(3)", "(4)", type="latex", out="Documents/GitHub/econThesisSpring/stargazertest.htmL")) # file name and loc

tableTEST <- stargazer(mod1, mod2, mod3, mod4, title="Linear Panel Regression Models of Rent Growth and Rent-Price-Ratio", header=FALSE, se=se, type="html", out = "stargazerOutputTest.html")

tableTEST
```

```{r}
# note: i'm going to do some data manipulation and add in some of the ACS variables when i pull in data from the census 


```




