---
title: "summaryStats"
author: "Maria Heeter"
date: "3/30/2022"
output: html_document
---

# set up 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(DT)
library(sjPlot)
library(skimr)
library(flextable)
```

# load in data 
```{r}
# imports ACS dataframe 
df <- read.csv("thesisDF.csv")
```

# makes into panel 

```{r}
df_panel <- panel_data(df, id = fips, wave = year)
df_panel

summary(df_panel)

# my vars select 
myvars <- c("mean_nom_housing_value", "mean_nom_contract_rent", "rent_price_ratio_national", "rent_price_ratio", "housing_value", "contract_rent") # see which to incl 
df_panel_sum <- df_panel[myvars]

# renames vars 
df_panel_sum <- rename(df_panel_sum, avgHV = housing_value)
df_panel_sum <- rename(df_panel_sum, avgRt = contract_rent)
df_panel_sum <- rename(df_panel_sum, avgRPR = rent_price_ratio)

# gens sum stast 
sumStats <- summary(df_panel_sum, avgHV, avgRt, avgRPR, year)
datatable(sumStats)

# cuts off decimal & renames
sumStats$Variable <- sumStats$skim_variable
sumStats$Histogram <- sumStats$numeric.hist
sumStats$Mean <- format(round(sumStats$numeric.mean, 2), nsmall=2)
sumStats$numeric.sd <- format(round(sumStats$numeric.sd, 2), nsmall=2)
sumStats$P0 <- format(round(sumStats$numeric.p0, 2), nsmall=2)
sumStats$P50 <- format(round(sumStats$numeric.p50,2), nsmall=2)
sumStats$P100 <- format(round(sumStats$numeric.p100, 2), nsmall=2)
sumStats$Year <- as.numeric(gsub(",", "", sumStats$year))

sumStats <- sumStats %>% dplyr::select(Variable, Year, Mean, P0, P50, P100)

set_flextable_defaults(font.family="Times New Roman")
flexTableStats <- flextable(sumStats)
flexTableStats <- theme_vanilla(flexTableStats)
flexTableStats


save_as_docx("my table 1" = flexTableStats, path = "sumStatsTable.docx")
print(flexTableStats, preview="docx")


```