---
title: "Plots"
author: "Maria Heeter"
date: "3/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(censusapi)
library(tidycensus)
library(tidyverse)
library(viridis)
library(dplyr)
library(tidyr)
library(reshape2)
# maps 
library(maps)
library(usmap)
library(ggplot2)
library(ggthemes)
library(stringr)
library(latticeExtra)
# Checks if package is installed, installs if necessary, and loads package for current session

pacman::p_load(
  lubridate,  # general package for handling and converting dates  
  linelist,   # has function to "guess" messy dates
  aweek,      # another option for converting dates to weeks, and weeks to dates
  zoo,        # additional date/time functions
  tidyverse,  # data management and visualization  
  rio)        # data import/export
```

## import in datasets 

```{r}
# imports CPI Rent/ HPI sep graph 
RentHpiSep <- read_excel("CPI Rent and HPI (separated).xls",skip = 11)

# imports joint CPI/HPI graph 
RentHpiJoint <- read_excel("All-Transactions House Price Index for the United States:Consumer Price Index for All Urban Consumers- Rent of Primary Residence in U.S. City Average.xls", 
    skip = 10)

df <- read.csv("thesisDF.csv")
view(df)
```

## Fed Plot 1 

```{r, echo=FALSE}
library("ggplot2")
library("ggthemes")
library("stringr")

joinedPlot <- ggplot(RentHpiJoint, aes(x=observation_date,y=RentHpiJoint$USSTHPI_CUUR0000SEHA )) + geom_line() + ylab("Index 1980:Q1=100/Index 1982-1984=100") + xlab("Date of Observation") + labs(caption = "Sources: FHFA; BLS")

#labs(title = str_wrap("All-Transactions House Price Index for the United States/Consumer Price Index for All Urban Consumers: Rent of Primary Residence in U.S. City Average", 60))

joinedPlot + theme_stata()
```

## Fed Plot 2 
```{r}
sepPlot <-  ggplot() + geom_line(data = RentHpiSep, aes(x=observation_date...1, y=CUSR0000SEHC), color="blue") + geom_line(data=RentHpiSep, aes(x=observation_date...4, y=USSTHPI), color="red") + ylab("Index Dec 1982=100, Index 1980:Q1=100") + xlab("Date of Observation") + labs(caption="Sources: FHFA; BLS")

sepPlot + theme_stata()
```

# map building 

```{r}

# map building 
usmap::plot_usmap(regions = "counties") # sample map 

# take the average of each of these values 

rent_price_ratio_map <- plot_usmap(data = df, values="mean_rent_price_ratio", include = c(df$fips), color="black") + scale_fill_gradientn(name="Average Rent-Price Ratio (2006-2019)", colours = c("blue", "white", "darkred"), label = scales::comma) + theme(legend.position="right")
rent_price_ratio_map # fix label 

housing_value_map <- plot_usmap(data = df, values="mean_housing_value", include = c(df$fips), color="black") + scale_fill_gradientn(name="Average Housing Value (2006-2019)", colours = c("blue", "white", "darkred"), label = scales::comma) + theme(legend.position="right")
housing_value_map 

rent_value_map <- plot_usmap(data = df, values="mean_contract_rent", include = c(df$fips), color="black") + scale_fill_gradientn(name="Average Contract Rent (2006-2019)", colours = c("blue", "white", "darkred"), label = scales::comma) + theme(legend.position="right")
rent_value_map 

# rent growth gradient map 

rent_growth_map <- plot_usmap(data = df, values="mean_rent_pct_change", include = c(df$fips), color="black") + scale_fill_gradientn(name="Average Rent Percent Change (2006-2019)", colours = c("blue", "white", "darkred"), breaks=c(10,-20), label = scales::comma) + theme(legend.position="right")
rent_growth_map 
                       
# housing percent change in growth take 1 

housing_growth_map <- plot_usmap(data = df, values="mean_housing_growth", include = c(df$fips), color="black") + scale_fill_continuous(low="blue", high="red", name="Median Housing Growth (2006-2019)", label=scales::comma) + theme(legend.position="right")
housing_growth_map 

# housing percent change in growth take 2 

housing_growth_map <- plot_usmap(data = df, values="mean_housing_growth", include = c(df$fips), color="black") + scale_fill_gradientn(name="Average Housing Price Growth (2006-2019)", colours = c("blue", "white", "red"), breaks=c(10,-20), label = scales::comma) + theme(legend.position="right")
housing_growth_map
                                                                                                          
# how to make negative: https://stackoverflow.com/questions/63004413/r-usmap-how-to-show-two-different-colors-one-for-gradients-in-positive-value
```

```{r}
# generally, are there other demographics that could be helpful?

# population 
# income 
# racial demographics 
# employment rates 
# age 

# hundreds of thousands 

# do everything w counties 
# maybe sub samples w different criteria later 

# do summary stats... data visualization 
# mapping 
# by county averaging rent price ratio over time period, mapping that # visualize rate of change by county 

# combo of time plots and maps 
# is there variation? are there patterns in the variation? 

# notes on summary stats for time series 

# sum doesn't deliniate cross sectional data (but include in appencix)
# time plots, maps 
# rent-price ratio figure & map. avg rent-price ratio overtime 

# three plots: 
# rent over time, hp over time & ratio 

```

# actual summary stats section 

```{r}

# avg rent over time 


# makes new cols. 1) average rent by all counties, 2) avg contract rent, 3) price-rent ratio 

df <- df %>% group_by(year) %>% mutate(mean_mean_contract_rent = mean(mean_contract_rent)) %>% mutate(mean_mean_housing_value = mean(mean_housing_value)) %>% mutate(mean_mean_rent_price_ratio = mean(mean_rent_price_ratio))
view(df)

# makes a new col that's average HPI by all counties 

# makes a new col that's avg rent-price ratio 

# line plot of contract rent over time 

mean_contract_rent_plot <- df %>% ggplot(aes(x=year, y = mean_mean_contract_rent, color="red")) + geom_line()
mean_contract_rent_plot  

# plot of hp over time 

mean_housing_value_plot <- df %>% ggplot(aes(x=year, y = mean_mean_housing_value, color="red")) + geom_line()
mean_housing_value_plot

# join the two plots 

sepPlot <- ggplot() + geom_line(data = df, aes(x=year, y=mean_mean_contract_rent), color="blue") + geom_line(data=df, aes(x=year, y=mean_mean_housing_value, color="red"))
sepPlot # NOTE: not an index 
                                                                                                  # # another attempt to divide        

obj1 <- xyplot(mean_mean_contract_rent ~ year, df, type="l", lwd=2)
obj2 <- xyplot(mean_mean_housing_value ~ year, df, type = "l", lwd=2)
doubleYScale(obj1, obj2, text=c("rent", "housing value"), add.ylab2=TRUE) 

# plot of rent price ratio over time 

mean_price_rent_ratio_plot <- df %>% ggplot(aes(x=year, y = mean_mean_rent_price_ratio, color="red")) + geom_line() 
mean_price_rent_ratio_plot

# another attempt, with an index. here we need the first year (2009), then divide all years by 2009 and multiply by 100. then plot those. 

# adds index column to plot 

df <- df %>% mutate(rentIndex = (mean_mean_contract_rent/51161.71)*100) # where the number is the 2009 mean contract rent!! 
df <- df %>% mutate(houseIndex = (mean_mean_housing_value/200618.2)*100)
view(df)

# adds rent_price_ratio from mean_mean values to the plot 

df <- df %>% mutate(rent_price_ratio_national=mean_mean_contract_rent/mean_mean_housing_value)
view(df) # i actually don't think we should have done it this way 

df <- df %>% mutate(rent_price_ratio_national_index = rentIndex/houseIndex)

# now, plot above (taking same template as fed plot)

indexPlot <-  ggplot() + geom_line(data = df, aes(x=year, y=rentIndex), color="blue") + geom_line(data=df, aes(x=year, y=houseIndex), color="red") + ylab("Index 2009=100") + xlab("Date of Observation") + labs(caption="Sources: Census 1-Year ACS")

indexPlot + theme_stata()

```
## makes years into dates; adds date column 

```{r}

# need to make sure year column is "as date" 
# here, i'm trying to make year column as date 

df <- df %>% mutate(month = 01) %>% mutate(day = 01)
view(dfTEST)

# need to make month, days into integer instead of numeric 

df$month <- as.character(dfTEST$month)
df$day <- as.character(dfTEST$day)
df$year <- as.character(dfTEST$year)

# checking class 
class(df$day)
class(df$month)
class(df$year)
# all are integers 

# now create new col named as "Date" by combining cols 
df$Date <- as.Date(with(df, paste(year,month,day,sep='-')), "%Y-%m-%d")
view(dfT)
```

# plots here 

```{r}
ratioPlot <- df %>% ggplot(aes(x=year,y=rent_price_ratio_national_index)) + geom_line() + ylab("Rent Index 2009=100/Housing Index 2009=100") + xlab("Date of Observation") + labs(caption = "Sources: Census 1-Year ACS")

#labs(title = str_wrap("All-Transactions House Price Index for the United States/Consumer Price Index for All Urban Consumers: Rent of Primary Residence in U.S. City Average", 60))

ratioPlot #+ theme_stata()

```

## just plain summary stats 

```{r}
summary(df)
ts <- ts(df)
summary(ts)
```

# save DF 
```{r}
write.csv(df, "thesisDF.csv", row.names=TRUE, quote=FALSE) 
```

# more plot options 
```{r}
# https://www.econometrics-with-r.org/14.2-tsdasc.html 
```
