---
title: "thesisPlots2ndDraft"
author: "Maria Heeter"
date: "3/21/2022"
output: html_document
---

```{r setup, include=FALSE,message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(censusapi)
library(tidycensus)
library(tidyverse)
library(viridis)
library(dplyr)
library(tidyr)
library(reshape2)
# maps 
library(maps)
library(usmap)
library(ggplot2)
library(ggthemes)
library(stringr)
library(latticeExtra)
# charting 
library(scales)
library(ggrepel)
# For manipulating data
library(magrittr)
library(rprojroot)
library(forcats)
library(dplyr)
library(tidyr)
library(readr)
library(lubridate)
# For descriptive statistics and graphing
library(skimr)
library(ggplot2)
library(scales)
library(gridExtra)
library(panelr)
# charts 
library(ggplot2)
library(ggthemes)
library(stringr)
```

## Import in datasets 

```{r, message=FALSE}
# imports CPI Rent/ HPI sep data (FRED) 
RentHpiSep <- read_excel("CPI Rent and HPI (separated).xls",skip = 11)

# imports joint CPI/HPI graph (FRED)
RentHpiJoint <- read_excel("All-Transactions House Price Index for the United States:Consumer Price Index for All Urban Consumers- Rent of Primary Residence in U.S. City Average.xls", 
    skip = 10)
 
# imports ACS dataframe 
df <- read_csv("thesisDF.csv")
```

# Main plots (rent, hp, rent/hp overtime)

```{r real hp overtime, message=FALSE}
# # title: Real house prices 
# df$commaMeanMeanRealHV <- comma(df$mean_mean_real_housing_value)
# 
# plot1 <- ggplot(df, aes(x=as.Date(date), y=mean_mean_real_housing_value)) + geom_line() + labs(caption ="Source: 1-Year American Community Survey") + scale_y_continuous(label=comma) + ylab("Dollars")
# 
# plot1 + theme_bw()+ theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust=2)) + theme(axis.title.x=element_blank()) +  theme(axis.title.y=element_text(angle=0, vjust=1)) # rotates years, makes y label horizontal 
# 
# # title - nominal house prices 
# plot7 <- ggplot(df, aes(x=as.Date(date), y=mean_mean_nom_housing_value)) + geom_line() + labs(caption ="Source: 1-Year American Community Survey") + ylab("Dollars") + xlab("Date of Observation") + scale_y_continuous(label=comma)
# 
# plot7 + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + theme(axis.title.x=element_blank()) +  theme(axis.title.y=element_text(angle=0, vjust=1))
```
# ABOVE, REDONE! 

```{r}

# title: Real house prices
df$commaMeanMeanRealHV <- comma(df$mean_real_housing_value)

plot1 <- ggplot(df, aes(x=as.Date(date), y=mean_real_housing_value)) + geom_line() + labs(caption ="Source: 1-Year American Community Survey") + scale_y_continuous(label=comma) + ylab("Dollars")

plot1 + theme_bw()+ theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust=2)) + theme(axis.title.x=element_blank()) +  theme(axis.title.y=element_text(angle=0, vjust=1)) # rotates years, makes y label horizontal

# title - nominal house prices
plot7 <- ggplot(df, aes(x=as.Date(date), y=mean_nom_housing_value)) + geom_line() + labs(caption ="Source: 1-Year American Community Survey") + ylab("Dollars") + xlab("Date of Observation") + scale_y_continuous(label=comma)

plot7 + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + theme(axis.title.x=element_blank()) +  theme(axis.title.y=element_text(angle=0, vjust=1))



```


```{r rents overtime, message=FALSE}
# title= Real contract rents 
# plot2 <- ggplot(df, aes(x=as.Date(date), y=mean_real_contract_rent)) + geom_line() + labs(caption ="Source: 1-Year American Community Survey") + ylab("Dollars") + xlab("Date of Observation") + scale_y_continuous(label=comma) 
# 
# #plots
# plot2 + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + theme(axis.title.x=element_blank()) +  theme(axis.title.y=element_text(angle=0, vjust=1)) 
# 
# # title = nominal contract rents 
# plot6 <- ggplot(df, aes(x=as.Date(date), y=mean_nom_contract_rent)) + geom_line() + labs(caption ="Source: 1-Year American Community Survey") + ylab("Dollars") + xlab("Date of Observation") + scale_y_continuous(breaks = c("8,665" = 8665, "8,860"= 8860, "8,855" = 8855, "8,865" = 8865), limits=c(8500,9000))  
# 
# plot6 + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + theme(axis.title.x=element_blank()) +  theme(axis.title.y=element_text(angle=0, vjust=1))

```

# above, REDONE!!! using new mean value 

```{r}
plot2 <- ggplot(df, aes(x=as.Date(date), y=mean_real_contract_rent)) + geom_line() + labs(caption ="Source: 1-Year American Community Survey") + ylab("Dollars") + xlab("Date of Observation") + scale_y_continuous(label=comma) 

#plots
plot2 + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + theme(axis.title.x=element_blank()) +  theme(axis.title.y=element_text(angle=0, vjust=1)) 

# title = nominal contract rents 
plot6 <- ggplot(df, aes(x=as.Date(date), y=mean_nom_contract_rent)) + geom_line() + labs(caption ="Source: 1-Year American Community Survey") + ylab("Dollars") + xlab("Date of Observation") + scale_y_continuous(label=comma) 

plot6 + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + theme(axis.title.x=element_blank()) +  theme(axis.title.y=element_text(angle=0, vjust=1))

```

```{r rent and house index, message=FALSE}
# title= Real contract rents, house prices (index)
plot3 <-  ggplot() + geom_line(data = df, aes(x=as.Date(date), y=houseIndex), color="blue") + geom_line(data=df, aes(x=as.Date(date), y=rentIndex), color="red") + ylab("Index") + xlab("Date of Observation") 

plot3 + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + theme(axis.title.x=element_blank()) + labs(caption="Source: 1-Year American Community Survey") + geom_text_repel(aes(x=as.Date(df$date[6500]), y=122, label="Real rents")) + geom_text_repel(aes(x=as.Date(df$date[7500]), y=110, label="Real house prices")) + theme(axis.title.y=element_text(angle=0))
```


```{r}

# title= Rent-price ratio PLAIN 
plot4 <- ggplot(df, aes(x=as.Date(date), y=(mean_nom_contract_rent/mean_nom_housing_value))) + geom_line() + labs(caption ="Source: 1-Year American Community Survey") + ylab("Ratio") + xlab("Date of Observation") 

plot4 + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + theme(axis.title.x=element_blank()) + theme(axis.title.y=element_text(angle=0)) + scale_y_continuous(breaks = c(".047" = 0.047, ".046"= 0.046, ".045" = 0.045 , ".044" = 0.044, ".043" = 0.043, ".042"=0.042))

# seeing overlay 
```

# nominal prices 

```{r}
# nominal Hp overtime 
plot5 <- ggplot(df, aes(x=as.Date(date), y=mean_nom_housing_value)) + geom_line() + labs(caption ="Source: 1-Year American Community Survey") + ylab("Dollars") + scale_y_continuous(label=comma)

plot5 + theme_classic() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + theme(axis.title.x=element_blank()) +  theme(axis.title.y=element_text(angle=0)) # rotates years, makes y label horiz

# nominal rent 
plot6 <- ggplot(df, aes(x=as.Date(date), y=mean_nom_contract_rent)) + geom_line() + labs(caption ="Source: 1-Year American Community Survey") + ylab("Dollars") + scale_y_continuous(label=comma)

plot6 + theme_classic() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + theme(axis.title.x=element_blank()) +  theme(axis.title.y=element_text(angle=0)) # rotates years, makes y label horiz

```

# descriptive stats using panelr package 

```{r}
# groups counties; makes df 
df_panel <- panel_data(df, id=fips, wave=year) 

# trying to fix dates 
df_panel<- panel_data(df, id=fips, wave=year)
df_panel$year <- as.double(df_panel$year)

df_panel_filtered_rent <- df_panel %>% filter(real_contract_rent < 1000000000)


# real contract rent per county overtime 

# filter for contract rent subset 
line_plot(df_panel_filtered_rent, real_contract_rent, add.mean=TRUE, alpha=.2) + scale_x_continuous(breaks=2009:2019) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_y_continuous(label=comma) + ylab("Dollars") + xlab("") +
  theme(axis.title.y=element_text(angle=0))

# non filtered contract rent subset 
line_plot(df_panel, real_contract_rent, add.mean=TRUE, alpha=.2) + scale_x_continuous(breaks=2009:2019) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ylab("Dollars") + xlab("") + theme(axis.title.y=element_text(angle=0)) + ylim(0,200000) 

# real hp per county overtime 
line_plot(df_panel, real_housing_price, add.mean=TRUE, alpha=.2, line.size = .3) + scale_x_continuous(breaks=2009:2019) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ylab("Dollars") + scale_y_continuous(label=comma) + xlab("")+ labs(caption ="Source: 1-Year American Community Survey") + theme(axis.title.y=element_text(angle=0)) + xlab("")

# real contract rent per county in ca
line_plot(df_panel, real_contract_rent, overlay = FALSE, subset.ids = filter(df_panel, state_name == "New Hampshire")$fips, add.mean==TRUE)  # insert real county name 

# line by state - need to get mean rent and hp by state 
# HERE

# rent price ratio per county 
line_plot(df_panel, rent_price_ratio, add.mean=TRUE, alpha=.2) + scale_x_continuous(breaks=2009:2019) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + theme(axis.title.y=element_text(angle=0)) + ylab("Ratio") + xlab("")

# national rent price ratio 
line_plot(df_panel, rent_price_ratio_national)


# house perc change per county 
line_plot(df_panel, house_perc_change_nominal, add.mean=TRUE, alpha=.2, line.size = .25) + ylab("Percent change") + xlab("") + scale_x_continuous(breaks=2009:2019) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + theme(axis.title.y=element_text(angle=0)) 

# scale_x_ cont gets rid of year decimal pts 
```

# Map building (in progress)

```{r, results='hide'}
usmap::plot_usmap(regions = "counties") # sample map: counties

# notes:
# show which places have the greatest rent growth over time 
# show which places have greatest housing value growth over time 
# show which counties have greatest perc change (growth) in rent-price ratio 

# housing perc change in years 2009-2013. half and half 

# after 2013 rent pct change 
housing_growth_map_14 <- plot_usmap(data=df[df$date >"2013-01-01",], values="mean_rent_pct_change", include=c(df$fips), color="black" )

# 2009 - 2013 
housing_growth_map_09 <- plot_usmap(data=df[df$date <="2013-01-01", ], values="mean_rent_pct_change", include=c(df$fips), color="black")


# adds constant value for mapping 
df$constant_value <- 1

# counties that are included 

counties_included_map <- plot_usmap(data=df, values = "constant_value", include=c(df$fips), color="black", labels=FALSE) + theme(legend.position = "none")
counties_included_map



# housing perc change in years 2014-2019. half and half 

```

# FRED VIZ 

```{r}
# imports CPI Rent/ HPI sep graph 
library(readr)
rentPriceRatioFRED <- read_csv("rentPriceRatioFRED.csv", 
    skip = 10)

# imports joint CPI/HPI graph 
RentHpiJoint <- read_excel("All-Transactions House Price Index for the United States:Consumer Price Index for All Urban Consumers- Rent of Primary Residence in U.S. City Average.xls", 
    skip = 10)
```

```{r, echo=FALSE}
# rent price ratio chart 
joinedPlot <- rentPriceRatioFRED %>% ggplot(aes(x=observation_date,y=CUUR0000SEHA_USSTHPI)) + geom_line() + ylab("Index") + labs(caption = "Sources: FHFA; BLS; FRED") + xlab("")
                                      

joinedPlot + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + theme(axis.title.y=element_text(angle=0)) 

# PREV Y: "1982-1984=100/Index 1980:Q1=100"
# title:"All-Transactions House Price Index for the United States/Consumer Price Index for All Urban Consumers: Rent of Primary Residence in U.S. City Average"
```

```{r}
# sep real hp and rents 
sepPlot <-  ggplot() + geom_line(data = RentHpiSep, aes(x=observation_date...1, y=CUSR0000SEHC), color="blue") + geom_line(data=RentHpiSep, aes(x=observation_date...4, y=USSTHPI), color="red") + ylab("Index") + xlab("") + labs(caption="Sources: FHFA; BLS; FRED")  

sepPlot + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + theme(axis.title.y=element_text(angle=0)) + geom_text_repel(aes(x=RentHpiSep$observation_date...1[466], y=255, label="Real rents")) + geom_text_repel(aes(x=RentHpiSep$observation_date...1[360], y=450, label="Real house prices")) 

# PREX Y: "Index Dec 1982=100, Index 1980:Q1=100")
# title: 
```



